TRUTH = (
    "Have you ghosted someone?"
    "Have you ever walked in on your parents doing 'it'?",
    "Who was the last person you liked the most? Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "What’s the one thing you’re afraid to lose?",
    "Do you like someone as of the moment?",
    "One thing about your best friend you are jealous of?",
    "Would you cheat on your boyfriend for a rich guy?",
    "What is your biggest turn on?",
    "When’s the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "What’s the scariest thing you’ve ever done?",
    "Have you ever picked your nose and eaten it?",
    "When’s the last time you lied to your parents and why?",
    "Have you ever lied about your age to participate in a contest?",
    "Have you ever been caught checking someone out?",
               
                   "What is your biggest pet peeve?",
"Are you a dog person or a cat person and why?",
"What is your favorite board game?",
"What is the weirdest thing that you have ever eaten",
"What is your darkest fear",
"What is your biggest regret"
"Who is your crush?",
"What are you most self-conscious about",
"What lie have you told that actually hurt someone",
"What is the scariest dream that you’ve ever had",
"Why did you break up with your last boyfriend or girlfriend?",
"What do you look for in a boyfriend or girlfriend?",
"Who have you loved, but they didn’t love you back?",
"What do you really hope your parents never find out about?",
"When was the last time you lied?",
"When was the last time you cried?",
"What is a secret that you’ve never told anyone?",
"What is the biggest mistake you’ve ever made?",
"What is the most trouble you’ve been in?",
"What is the meanest thing anyone has ever done to you?",
"Have you ever cheated on a test?",
"What is your favorite childhood memory?",
"Who is your secret crush?",
"If you suddenly had the power of invisibility, what would you do?",
"If you could have one superpower what would it be?",
"Are you scared of the dark?",
"Do you write in a diary?",
"What is your crush’s personality like?",
"What do you find the most attractive in a person?",
"What do you find the least attractive in a person?"
"What is your greatest fear in a relationship?",
"How long was your longest relationship?",
"How do you think other people perceive you?",
"Do you believe in fate?",
"Do you believe in soulmates?",
"Do you believe in karma?",
"What do you do for fun?",
"What is the worst advice that you have ever received?",
"What is the worst thing in your life right now?",
"What was the strangest dream you have ever had?",
"When is Your Birthday?",
"What is the dumbest thing that you have ever done?",
"When is the last time you did something embarrassing and what was it?",
"Have you ever peed yourself? If so, when?",
"Have you ever pooped yourself? If so, when?",
"When have you got caught in a lie?",
"What is your most embarrassing vomit story?",
"What is the biggest thing that you’ve gotten away with?",
"Where is the strangest place you have peed?",
"What is the most embarrassing thing that your parents have caught you doing?",
"When was the most inappropriate time that you farted?",
"What is the grossest habit that you have?",
"What is the most embarrassing nickname that you have had?",
"What was the last thing you searched on your phone?",
"Have you ever walked in on your parents having sex?",
"Do you pick your nose?",
"Do you ever talk to yourself in the mirror?",
"Do you ever talk in your sleep or sleep walk?",
"When was a time that you embarrassed yourself in front of your crush?",
"Have you ever regretted something you did in order to get a crush’s attention?",
"What was your weirdest habit as a kid?",)

DARE = (
    "Show the most embarrassing photo on your phone",
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Eat a raw piece of garlic",
    "Do 100 squats",
    "Keep three ice cubes in your mouth until they melt",
    "Say something dirty to the person on your leftYou've got company!",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it",
    "*Yell out the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Remove four items of clothing",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Keep your eyes closed until it's your go again",
    "Send a sext to the last person in your phonebook",
    "Show off your orgasm face",
    "Seductively eat a banana",
    "Empty out your wallet/purse and show everyone what's inside",
    "Do your best sexy crawl",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone else in the group",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell the saddest story you know",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Put as many snacks into your mouth at once as you can",
    "Send your most recent selfie.",
    "Send your ugliest selfie.",
    "Send a screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send a screenshot of your messenger inbox",
    "Tell something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your homescreen.",
    "Send a cover of your favorite song. 🎤",
    "Do a lyric prank on someone and send proof.",
    "Confess to your current crush. ❤️",
    "Declare who is your true love.",
    "Send a screenshot of your gallery.",
    "Set your crush’s picture as your dp.",
    "Suggest me more dares.",
)
